<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */

/**
 * Define constants that
 * are normally defined in !inc.php
 * because we not including !inc.php for tests
 *
 */
define('LAMPCMS_DEBUG', false);
define('MOCK_SALT', 'abcde');
define('MOCK_COOKIE_SALT', 'abcde');

define('DEFAULT_LANG', 'en');
define('COOKIE_DOMAIN', '' );
define('SITE_URL', '' );
define('IMAGE_SITE', 'http://img.lampcms.com');
define('AVATAR_IMG_SITE', 'http://img.lampcms.com');

if(!defined('MONGO_DBNAME')){
	define('MONGO_DBNAME', 'LAMPCMS_TEST');
}

/**
 * LAMPCMS_PATH may be defined
 * in Eclipse in External Tools Configuration
 * > Enviromnent just add LAMPCMS_PATH and
 * point value to the root dir of your project
 * ..
 * @var string
 */
$path = getenv('LAMPCMS_PATH');
if(!defined('LAMPCMS_PATH')){
	if($path){
		define('LAMPCMS_PATH', $path);
	} else {
		define('LAMPCMS_PATH', './'); // this looks wrong maybe? Why path is this dir?
		echo ' LAMPCMS PATH: '.LAMPCMS_PATH;
	}
}
define('LAMPCMS_WWW_DIR', LAMPCMS_PATH.DIRECTORY_SEPARATOR.'www'.DIRECTORY_SEPARATOR);
define('LAMPCMS_DATA_DIR', LAMPCMS_WWW_DIR.'w'.DIRECTORY_SEPARATOR);

/**
 * Set all the multibyte
 * functions to use UTF-8
 * as internal encoding
 */
if(function_exists('mb_internal_encoding')){
	mb_internal_encoding("UTF-8");
}

/**
 * if php NOT running as fastcgi
 * then we need to create a dummy function
 *
 */
if(!function_exists('fastcgi_finish_request')){
	define('NO_FFR', true);
	function fastcgi_finish_request(){}
}

$libDir = LAMPCMS_PATH.DIRECTORY_SEPARATOR.'lib';
$lampcmsClasses = $libDir.DIRECTORY_SEPARATOR.'Lampcms'.DIRECTORY_SEPARATOR;

require 'LampcmsUnitTestCase.php';

require $lampcmsClasses.'Interfaces'.DIRECTORY_SEPARATOR.'All.php';
require $lampcmsClasses.'Exception.php';
require $lampcmsClasses.'Object.php';
require $lampcmsClasses.'SplClassLoader.php';
require LAMPCMS_PATH.DIRECTORY_SEPARATOR.'Points.php';

function d($message){}

function e($message){}

require LAMPCMS_PATH.DIRECTORY_SEPARATOR.'autoload.php';


