<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */


namespace Lampcms;
require_once 'bootstrap.php';

require_once 'Fixtures/MockUser.php';


use Lampcms\User;

/**
 * Must be run after MongoDocTest
 * 
 * 
 * @author admin
 *
 */
class UserTest extends LampcmsUnitTestCase
{
	/**
	 * Collection names used in this test
	 * Enter description here ...
	 * @var unknown_type
	 */
	protected $aCollections = array('USERS');

	protected $oUser;

	public function setUp(){
		$this->oUser = \Lampcms\MockUser::factory(new Registry());
	}


	public function testFactory(){
		$o = \Lampcms\User::factory(new Registry());
		$o->setSaved();
		$this->assertTrue($o instanceof \Lampcms\User);
	}


	public function testGetRoleId(){

		$this->assertEquals('registered', $this->oUser->getRoleId());
	}


	/**
	 * @depends testGetRoleId
	 */
	public function testSetRoleId(){
		$this->oUser->setRoleId('unactivated');
		$this->assertEquals('unactivated', $this->oUser->getRoleId());
	}

	/**
	 * @depends testGetRoleId
	 */
	public function testSetRoleIdByAssignment(){
		$this->oUser['role'] = 'unactivated';
		$this->assertEquals('unactivated', $this->oUser->getRoleId());
	}


	/**
	 * @depends testGetRoleId
	 */
	public function testSetBadRoleId(){
		try{
			$this->oUser->setRoleId('badrole');
		} catch (\Lampcms\DevException $e){
			return;
		}

		$this->fail('\Lampcms\DevException expected when trying to add role that is not on the acl.ini');
	}

	/**
	 * @depends testGetRoleId
	 */
	public function testSetBadRoleIdByAssignment(){
		try{
			$this->oUser['role'] = 'badrole';
		} catch (\Lampcms\DevException $e){
			return;
		}

		$this->fail('\Lampcms\DevException expected when trying to add role that is not on the acl.ini');
	}

	/**
	 * @depends testSetRoleId
	 *
	 */
	public function testActivate(){
		$this->oUser->setRoleId('unactivated');
		$this->oUser->activate();
		$this->assertEquals('registered', $this->oUser->getRoleId());
	}


	public function testGetAge(){
		$age = $this->oUser->getAge();
		$this->assertTrue(is_numeric($age));
		$this->assertTrue(is_string($age));
		$this->assertTrue( 20 < (int)$age && 100 > (int)$age);
	}


	public function testGetAvatarSrc(){
		$s = $this->oUser->getAvatarSrc();
		$this->assertEquals('http://img.lampcms.com/w/img/avatar/sqr/1A.jpg', $s);

	}

	/**
	 * @depends testGetAvatarSrc
	 *
	 */
	public function testGetAvatarSrcNoCache(){
		$s = $this->oUser->getAvatarSrc(true);
		$this->assertTrue(false !== (strstr($s, 'http://img.lampcms.com/w/img/avatar/sqr/1A.jpg?id=1')) );

	}

	/**
	 * @depends testGetAvatarSrc
	 *
	 */
	public function testGetAvatarImgSrc(){
		$s = $this->oUser->getAvatarImgSrc();
		$this->assertEquals('<img src="http://img.lampcms.com/w/img/avatar/sqr/1A.jpg" class="img_avatar" width="40" height="40" border="0" alt="avatar"/>', $s);
	}

	public function testGetFullName(){
		$this->assertEquals('John D Doe', $this->oUser->getFullName());
	}

	/**
	 * @depends testGetFullName
	 *
	 */
	public function testGetDisplayName(){
		$this->assertEquals('John D Doe', $this->oUser->getDisplayName());

		$this->oUser->offsetUnset('fn');
		$this->oUser->offsetUnset('mn');
		$this->oUser->offsetUnset('ln');
		$this->oUser->setSaved();

		$this->assertEquals('ladada', $this->oUser->getDisplayName());
	}


	public function testGetLocation(){
		$this->assertEquals('Stroudsburg, PA United States', $this->oUser->getLocation());
	}

	public function testGetProfileUrl(){
		$this->assertEquals('/users/26/ladada', $this->oUser->getProfileUrl());
	}


	public function testGetReputation(){
		$this->assertEquals(1, $this->oUser->getReputation());
	}

	/**
	 * @depends testGetReputation
	 *
	 */
	public function testSetReputation(){
		$this->oUser->setReputation(0);
		$this->assertEquals(1, $this->oUser->getReputation());
		$this->oUser->setReputation(25);
		$this->assertEquals(26, $this->oUser->getReputation());
		$this->oUser->setSaved();
	}


	public function testAssignReputation(){
		try{
			$this->oUser['i_rep'] = 10;
		} catch (\Lampcms\DevException $e){
			return;
		}

		$this->fail('\Lampcms\DevException is expected when assigning value of i_rep');
	}


	public function testGetUid(){
		$this->assertEquals(26, $this->oUser->getUid());
		$this->oUser->offsetUnset('_id');
		$this->oUser->setSaved();
		$this->assertEquals(0, $this->oUser->getUid());
	}

	public function testGetUrl(){
		$this->assertEquals('<a rel="nofollow" href="http://www.lampcms.com">http://www.lampcms.com</a>', $this->oUser->getUrl());
	}

	public function testIsGuest(){
		$this->assertFalse($this->oUser->isGuest());
	}

	/**
	 * @depends testGetRoleId
	 *
	 */
	public function testIsModerator(){
		$this->assertFalse($this->oUser->isModerator());
		$this->oUser->setRoleId('moderator');
		$this->assertTrue($this->oUser->isModerator());
		$this->oUser->setRoleId('administrator');
		$this->assertTrue($this->oUser->isModerator());
		$this->oUser->setSaved();
	}

	public function testSetLastActive(){
		$now = time();
		$this->oUser->setLastActive();
		$this->assertTrue( ($this->oUser['i_lm_ts'] - $now) < 2 );
		sleep(3);
		$this->assertFalse((time() - $now) < 2);
		$this->oUser->setLastActive();
		$this->assertTrue( ($this->oUser['i_lm_ts'] - $now) < 2 );
		$this->oUser->setSaved();
	}


	public function testSetTime(){
		$this->oUser->setTime();
		$this->assertEquals('Atlantic/Azores', \date_default_timezone_get());
	}

	/**
	 * @depends testSetTime
	 *
	 */
	public function testSetGetTimezone(){
		$this->oUser->setTimezone('Europe/London');
		$this->assertEquals('Europe/London', $this->oUser->getTimezone());

		$this->oUser->setTimezone('Europe/Helsinki');
		$this->assertEquals('Europe/Helsinki', $this->oUser->getTimezone());

		$this->oUser->setTimezone('Africa/Abidjan');
		$this->assertEquals('Africa/Abidjan', $this->oUser->getTimezone());

		$this->oUser->setTimezone('Atlantic/Bermuda');
		$this->assertEquals('Atlantic/Bermuda', $this->oUser->getTimezone());

		$this->oUser->setTimezone('Australia/Melbourne');
		$this->assertEquals('Australia/Melbourne', $this->oUser->getTimezone());

		$this->oUser->setTimezone('America/Argentina/San_Luis');
		$this->assertEquals('America/Argentina/San_Luis', $this->oUser->getTimezone());

		$this->oUser->setTimezone('America/New_York');
		$this->assertEquals('America/New_York', $this->oUser->getTimezone());

		/**
		 * Setting Invalid timezone will not work
		 * previous value will still be there!
		 */
		$this->oUser->setTimezone('America/Bad_Time');
		$this->assertEquals('America/New_York', $this->oUser->getTimezone());

		$this->oUser->setSaved();
	}


	/**
	 * @depends testSetTime
	 *
	 */
	public function testSetTimezoneByAssignment(){
		$this->oUser['tz'] = 'America/New_York';
		$this->assertEquals('America/New_York', $this->oUser->getTimezone());

		$this->oUser['tz'] = 'America/Bad_Time';
		$this->assertEquals('America/New_York', $this->oUser->getTimezone());

		$this->oUser->setSaved();
	}
	
	public function testSave(){
		$oRegistry = new Registry();
		$this->oUser->offsetUnset('_id');
		$this->oUser->save();
		$a = $oRegistry->Mongo->USERS->findOne(array('username_lc' => 'ladada'));
		$this->assertTrue(is_array($a) && count($a) > 5);
	}
}
