<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website's Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */



namespace Lampcms;


class ProfileDiv extends LampcmsObject
{
	/**
	 * Created and returns html for the user profile div
	 *
	 * @todo translate string 'ago'
	 *
	 * @param Registry $oRegistry
	 * @param User $oUser
	 */
	public static function get(Registry $oRegistry, User $oUser){
		$edit = '';
		$lastActive = $oUser['i_lm_ts'];
		$lastActive = (!empty($lastActive)) ? $lastActive : $oUser['i_reg_ts'];
		$rep = $oUser->getReputation();

		d('rep: '.$rep);

		if($oRegistry->Viewer->getUid() === $oUser->getUid()){
			$edit = '<div class="fl middle"><span class="icoc key">&nbsp;</span><a href="/editprofile/" class="edit middle">Edit profile</a></div>';
		}

		$desc = Utf8String::factory($oUser['description'], 'utf-8', true)->linkify()->valueOf();

		$vars = array(
			'editLink' => $edit,
			'username' => $oUser->username,
			'avatar' => $oUser->getAvatarImgSrc(),
			'reputation' => $rep,
			'name' => $oUser->getDisplayName(),
			'genderLabel' => 'Gender',
			'gender' => self::translateGender($oUser['gender']),
			'since' => date('F j, Y', $oUser->i_reg_ts),
			'lastActivity' => TimeAgo::format(new \DateTime(date('r', $lastActive))),
			'website' => $oUser->getUrl(),
			'twitter' => $oUser->getTwitterUrl(),
			'age' => $oUser->getAge(),
			'facebook' => $oUser->getFacebookUrl(),
			'location' => $oUser->getLocation(),
			'description' => \wordwrap($desc, 50),
			'editRole' => Usertools::getHtml($oRegistry, $oUser),
			'followButton' => self::makeFollowButton($oRegistry, $oUser),
			'followers' => ShowFollowers::factory($oRegistry)->getUserFollowers($oUser),
			'following' => ShowFollowers::factory($oRegistry)->getUserFollowing($oUser)
		);

		return \tplUserInfo::parse($vars);
	}


	/**
	 * Get textual value of "Gender" M/F
	 *
	 * @todo translate string Male/Female
	 * @param string $gender
	 * @return string
	 */
	protected static function translateGender($gender){
		switch($gender){
			case 'M':
				$ret = 'Male';
				break;

			case 'F':
				$ret = 'Female';
				break;

			default:
				$ret = '';
		}

		return $ret;
	}


	/**
	 * Make a follow user button
	 * checks that user is not the same
	 * as viewer, otherwise just returns
	 * empty string
	 *
	 *
	 * @param Registry $oRegistry
	 * @param User $oUser use who to follow
	 * @return string html of "Follow" button
	 * of empty string if Viewer is same as User
	 *
	 */
	public static function makeFollowButton(Registry $oRegistry, User $oUser){

		$button = '';
		$oViewer = $oRegistry->Viewer;
		$uid = $oUser->getUid();

		if($uid !== $oViewer->getUid()){

			$aVars = array(
			'id' => $uid,
			'icon' => 'cplus',
			'label' => 'Follow',
			'class' => 'follow',
			'type' => 'u',
			'title' => 'Follow this user'
			);

			if(in_array($uid, $oViewer['a_f_u'])){
				$aVars['label'] = 'Following';
				$aVars['class'] = 'following';
				$aVars['icon'] = 'check';
				$aVars['title'] = 'You are following this user';
			}

			$button = '<div class="fl mt10 mb10"><div class="follow_wrap">'.\tplFollowButton::parse($aVars, false).'</div></div>';

		}

		return $button;
	}

	/*

	public function getShredButton(Registry $oRegistry, User $oUser){

	}*/
}