<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website's Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */



namespace Lampcms;

/**
 *
 * Class for rendering <div> with user profile
 * This class is used for generating div on page
 * /user/$id/
 *
 * @author Dmitri Snytkine
 *
 */
class ProfileDiv extends LampcmsObject
{
	/**
	 * Created and returns html for the user profile div
	 *
	 * @param Registry $oRegistry
	 * @param User $oUser
	 */
	public static function get(Registry $oRegistry, User $oUser){
		$edit = '';
		$lastActive = $oUser['i_lm_ts'];
		$lastActive = (!empty($lastActive)) ? $lastActive : $oUser['i_reg_ts'];
		$rep = $oUser->getReputation();

		d('rep: '.$rep);
		$uid = $oUser->getUid();
		$isSameUser = ($oRegistry->Viewer->getUid() === $uid);
		if($isSameUser || $oRegistry->Viewer->isModerator()){
			$edit = '<div class="fl middle"><span class="icoc key">&nbsp;</span><a href="/editprofile/'.$uid.'" class="edit middle">Edit profile</a></div>';
		}

		$desc = \trim($oUser['description']);
		$desc = (empty($desc)) ? '' : Utf8String::factory($desc, 'utf-8', true)->linkify()->valueOf();

		$vars = array(
			'editLink' => $edit,
			'username' => $oUser->username,
			'avatar' => $oUser->getAvatarImgSrc(),
			'reputation' => $rep,
			'name' => $oUser->getDisplayName(),
			'genderLabel' => 'Gender',
			'gender' => self::translateGender($oUser['gender']),
			'since' => date('F j, Y', $oUser->i_reg_ts),
			'lastActivity' => TimeAgo::format(new \DateTime(date('r', $lastActive))),
			'website' => $oUser->getUrl(),
			'twitter' => '<div id="my_tw">'.self::getTwitterAccount($oRegistry, $oUser, $isSameUser).'</div>',
			'age' => $oUser->getAge(),
			'facebook' => '<div id="my_fb">'.self::getFacebookAccount($oRegistry, $oUser, $isSameUser).'</div>',
			'tumblr' => '<div id="my_tm">'.self::getTumblrAccount($oRegistry, $oUser, $isSameUser).'</div>',
			'location' => $oUser->getLocation(),
			'description' => \wordwrap($desc, 50),
			'editRole' => Usertools::getHtml($oRegistry, $oUser),
			'followButton' => self::makeFollowButton($oRegistry, $oUser),
			'followers' => ShowFollowers::factory($oRegistry)->getUserFollowers($oUser),
			'following' => ShowFollowers::factory($oRegistry)->getUserFollowing($oUser)
		);

		return \tplUserInfo::parse($vars);
	}


	/**
	 * Get either the link to @username of Twitter account if user has one
	 * OR html for the button to connect Twitter account
	 * to Existing Account
	 *
	 *
	 * @param object $oRegistry
	 * @param object $oUser
	 *
	 * @return string html html of Connect button
	 * or just plain text string with @username
	 *
	 */
	public static function getTwitterAccount(Registry $oRegistry, User $oUser, $isSameUser){

		$t = $oUser->getTwitterUrl();
		if(!empty($t)){
			return $t;
		}


		if(extension_loaded('oauth') && $isSameUser){
			$aTwitter = $oRegistry->Ini->getSection('TWITTER');
			if(!empty($aTwitter['TWITTER_OAUTH_KEY']) && !empty($aTwitter['TWITTER_OAUTH_SECRET'])){
				return '<div id="connect_twtr" class="twsignin ajax ttt btn_connect rounded4" title="Connect Twitter Account"><img src="/images/tw-user.png" width="16" height="16"><span class="_bg_tw">Connect Twitter</span></div>';
			}
		}

		return '';
	}


	/**
	 * Get either the link to Tumblr blog
	 * if user has one
	 * OR html for the button to connect Tumblr account
	 * to Existing Account
	 *
	 *
	 * @param object $oRegistry
	 * @param object $oUser
	 *
	 * @return string html of Connect button
	 * or link to user's Tumblr blog
	 *
	 */
	public static function getTumblrAccount(Registry $oRegistry, User $oUser, $isSameUser){

		$t = $oUser->getTumblrBlogLink();
		d('tumblr blog url: '.$t);
		if(!empty($t)){
			return $t;
		}

		if(extension_loaded('oauth') && $isSameUser){
			$a = $oRegistry->Ini->getSection('TUMBLR');
			if(!empty($a) && !empty($a['OAUTH_KEY']) && !empty($a['OAUTH_SECRET'])){
				return '<div id="connect_tumblr" class="add_tumblr ajax ttt btn_connect rounded4" title="Connect Tumblr Blog"><img src="/images/tumblr_16.png" width="16" height="16"><span class="_bg_tw">Connect Tumblr Blog</span></div>';
			}
		}

		return '';
	}


	/**
	 * Get either the link to Facebook profile
	 * if user has one
	 * OR html for the button to connect Facebook account
	 * to Existing Account
	 *
	 *
	 * @param object $oRegistry
	 * @param object $oUser
	 *
	 * @return string html of Connect button
	 * or link to Facebook profile page
	 *
	 */
	public static function getFacebookAccount(Registry $oRegistry, User $oUser, $isSameUser){

		$f = $oUser->getFacebookUrl();
		if(!empty($f)){
			return $f;
		}

		if(extension_loaded('curl') && $isSameUser){
			$aFB = $oRegistry->Ini->getSection('FACEBOOK');
			if(!empty($aFB) && !empty($aFB['APP_ID'])){

				return '<div id="connect_fb" class="fbsignup ajax ttt btn_connect rounded4" title="Connect Facebook Account"><img src="/images/facebook_16.png" width="16" height="16"><span class="_bg_tw">Connect Facebook</span></div>';
			}
		}

		return '';
	}


	/**
	 * Get textual value of "Gender" M/F
	 *
	 * @todo translate string Male/Female
	 * @param string $gender
	 * @return string
	 */
	protected static function translateGender($gender){
		switch($gender){
			case 'M':
				$ret = 'Male';
				break;

			case 'F':
				$ret = 'Female';
				break;

			default:
				$ret = '';
		}

		return $ret;
	}


	/**
	 * Make a follow user button
	 * checks that user is not the same
	 * as viewer, otherwise just returns
	 * empty string
	 *
	 *
	 * @param Registry $oRegistry
	 * @param User $oUser use who to follow
	 * @return string html of "Follow" button
	 * of empty string if Viewer is same as User
	 *
	 */
	public static function makeFollowButton(Registry $oRegistry, User $oUser){

		$button = '';
		$oViewer = $oRegistry->Viewer;
		$uid = $oUser->getUid();

		if($uid !== $oViewer->getUid()){

			$aVars = array(
			'id' => $uid,
			'icon' => 'cplus',
			'label' => 'Follow',
			'class' => 'follow',
			'type' => 'u',
			'title' => 'Follow this user'
			);

			if(in_array($uid, $oViewer['a_f_u'])){
				$aVars['label'] = 'Following';
				$aVars['class'] = 'following';
				$aVars['icon'] = 'check';
				$aVars['title'] = 'You are following this user';
			}

			$button = '<div class="fl mt10 mb10"><div class="follow_wrap">'.\tplFollowButton::parse($aVars, false).'</div></div>';
		}

		return $button;
	}

}
