<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website's Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */


namespace Lampcms;


/**
 *
 * Class represeints one question stored
 * in Mongo QUESTIONS collection
 * implements LampcmsResourceInterface
 *
 * @author Dmitri Snytkine
 *
 */
class Question extends MongoDoc implements Interfaces\Question, Interfaces\UpDownRatable, Interfaces\CommentedResource
{
	/**
	 * Currently not used, was going to have
	 * method to get all answers for this question
	 * by quereing ansCollection
	 * but so far this is not required.
	 *
	 * It may be required later when implementhing
	 * something like an NNTP server
	 *
	 * @var string
	 */
	protected $ansCollection = 'ANSWERS';

	public function __construct(Registry $oRegistry, array $a = array()){

		parent::__construct($oRegistry, 'QUESTIONS', $a);
	}


	/**
	 * (non-PHPdoc)
	 * @see LampcmsResourceInterface::getResourceTypeId()
	 */
	public function getResourceTypeId(){
		return 'QUESTION';
	}

	/**
	 * (non-PHPdoc)
	 * @see ResourceInterface::getResourceId()
	 */
	public function getResourceId(){

		return $this->offsetGet('_id');
	}


	/**
	 * (non-PHPdoc)
	 * @see LampcmsResourceInterface::getDeletedTime()
	 */
	public function getDeletedTime(){

		return $this->offsetGet('i_del_ts');
	}

	/**
	 * (non-PHPdoc)
	 * @see LampcmsResourceInterface::getOwnerId()
	 */
	public function getOwnerId(){

		return (int)$this->offsetGet('i_uid');
	}


	/**
	 * (non-PHPdoc)
	 * @see LampcmsResourceInterface::getLastModified()
	 */
	public function getLastModified(){

		return $this->offsetGet('i_lm_ts');
	}


	/**
	 * Get value of i_etag but if it does
	 * not exist then return value of i_lm_ts
	 *
	 * @return int timestamp of last modification
	 */
	public function getEtag(){
		$ret = $this->offsetGet('i_etag');

		return (!empty($ret)) ? $ret : $this->offsetGet('i_lm_ts');
	}


	/**
	 * Get full (absolute) url for this question,
	 * including the http and our domain
	 *
	 * @return string url for this question
	 */
	public function getUrl(){

		return $this->oRegistry->Ini->SITE_URL.'/q'.$this->offsetGet('_id').'/'.$this->offsetGet('url');
	}


	/**
	 * Should return false if NOT closed
	 * otherwise either true or timestamp
	 * of when it was closed
	 *
	 * @todo change this to just return offsetGet('i_closed)
	 * it will return 0 if i_closed is not present
	 * because if the new way we going to handle non-existent
	 * offsets that start with 'i_' or end with 'id')
	 */
	public function isClosed(){
		$a = $this->offsetGet('a_closed');

		return (empty($a)) ? false : $a;
	}


	/**
	 * @return int number of answers this question has
	 */
	public function getAnswerCount(){

		return $this->offsetGet('i_ans');
	}


	/**
	 * Set time, reason for when question was closed
	 * as well as username and userid of user who closed it
	 *
	 * @param string $reason
	 * @param object $closer User who closed the question
	 *
	 * @return object $this
	 */
	public function setClosed(User $closer, $reason = null){

		if(!$this->checkOffset('a_closed')){
			$this->offsetSet('a_closed', array(
				'username' => $closer->getDisplayName(),
				'i_uid' => $closer->getUid(),
				'av' => $closer->getAvatarSrc(),
				'reason' => $reason,
				'hts' => date('F j, Y g:i a T')
			)
			);

		}

		return $this;
	}


	/**
	 *
	 * Mark this item as deleted but only
	 * if not already marked as deleted
	 *
	 * @param object User $user user marking this
	 * item as deleted
	 *
	 * @param string $reason optional reason for delete
	 *
	 * @return object $this
	 */
	public function setDeleted(User $user, $reason = null){
		if(0 === $this->getDeletedTime()){
			$this->offsetSet('i_del_ts', time());
			$this->offsetSet('a_deleted',
			array(
			'username' => $user->getDisplayName(),
			'i_uid' => $user->getUid(),
			'av' => $user->getAvatarSrc(),
			'reason' => $reason,
			'hts' => date('F j, Y g:i a T')
			)
			);
		}

		$this->touch();

		return $this;
	}


	/**
	 *
	 * Adds a_edited array of data to Question
	 *
	 * @param User $user
	 * @param string $reason reason for editing
	 *
	 * @return object $this
	 */
	public function setEdited(User $user, $reason = ''){

		$aEdited = $this->offsetGet('a_edited');
		if(empty($aEdited) || !is_array($aEdited)){
			$aEdited = array();
		}

		$aEdited[] = array(
			'username' => $user->getDisplayName(),
			'i_uid' => $user->getUid(),
			'av' => $user->getAvatarSrc(),
			'reason' => $reason,
			'hts' => date('F j, Y g:i a T'));

		$this->offsetSet('a_edited', $aEdited);

		$this->touch();

		return $this;
	}


	/**
	 *
	 * Set tags for this question
	 * It will also update "a_edited" array
	 * to record the retag action, records
	 * user who retagged, and "Retag" as reason for edit
	 * Will also update lastModified
	 *
	 * @param User $user object User who retagged this question
	 * @param array $tags array of tags
	 */
	public function retag(User $user, array $tags){

		$this->offsetSet('a_tags', $tags);
		$this->offsetSet('tags_html', \tplQtags::loop($tags, false));
		$this->offsetSet('tags_c', trim(\tplQtagsclass::loop($tags, false)));
		
		$b = $this->offsetGet('b');
		d('b: '.$b);
		
		$body = Bodytagger::highlight($b, $tags);

		$this->offsetSet('b', $body);

		$this->setEdited($user, 'Retagged');

		return $this;
	}


	/**
	 * Sets the id of best_answer,
	 * id of user that supplied best answer
	 * sets 'status' to 'accptd'
	 * and also updates the Answer object to the
	 * set accepted property to true
	 *
	 * In case question was 'unanswered' we must also
	 * update UNANSWERED_TAGS
	 *
	 * @param Answer $oAnswer object of type Answer represents
	 * Answer being accepted as best answer
	 *
	 */
	public function setBestAnswer(Answer $oAnswer){
		d('about to set status to accptd');
		$this->offsetSet('i_sel_ans', $oAnswer->getResourceId());
		$this->offsetSet('i_sel_uid', $oAnswer->getOwnerId());

		/**
		 * Now set the Answer object's accepted status to true
		 */
		$oAnswer->setAccepted();

		/**
		 * If Question is still not 'answered', means
		 * no accepted answer,
		 * then since we are not changing its status
		 * to answered, we must update
		 * the count of unanswered tags, which
		 * is done via UnansweredTags object
		 */
		if('accptd' !== $this->offsetGet('status')){
			UnansweredTags::factory($this->oRegistry)->remove($this);
		}

		$this->offsetSet('status', 'accptd');
		d('setting status to accptd');

		$this->touch(false);

		return $this;
	}


	/**
	 * Increases i_ans by $inc, which is usually 1
	 * but can also be used to decrease the count, by
	 * passing a negative value
	 *
	 * (non-PHPdoc)
	 * @see QuestionInterface::increaseAnswerCount()
	 *
	 * @param int $inc
	 */
	public function updateAnswerCount($inc = 1){
		$iAns = $this->offsetGet('i_ans');
		d('$iAns '.$iAns );
		$newCount = max(0, ($iAns + $inc));
		d('$newCount: '.$newCount);

		/**
		 * Set new value of i_ans but make sure
		 * it will never be less than 0
		 * This is just an extra guard, should not
		 * really happened, but passing a negative value
		 * is possible when we need to decrease answer count,
		 * that's why we need this guard here.
		 */
		$this->offsetSet('i_ans',  $newCount);

		/**
		 * Change the status to answrd
		 * 'answrd' is not the same as 'accptd'
		 * it simply serves a purpose to set the style
		 * of div to not be red, but it still does not
		 * make the question 'answered'
		 */
		if($newCount > 0){
			$this->offsetSet('status', 'answrd');
		} else {
			$this->offsetSet('status', 'unans');
		}

		/**
		 * If new value is NOT 1 then set
		 * a_s (plural suffix) to 's'
		 */
		if(1 !== ($newCount)){
			$this->offsetSet('ans_s', 's');
		} else {
			$this->offsetSet('ans_s', '');
		}

		$this->touch();

		return $this;
	}


	/**
	 * Updates last modified timestamp
	 * A replacement for updateLastModified() method
	 *
	 * @return object $this
	 */
	public function touch($etagOnly = false){
		$time = time();

		$this->offsetSet('i_etag', $time);
		if(!$etagOnly){
			$this->offsetSet('i_lm_ts', time());
		}

		return $this;
	}


	/**
	 * Logic: For guests dont check question owner id
	 * For others: insert into QUESTION_VIEWS first as a way
	 * to test for duplicates.
	 * Duplicates are: same uid and same qid
	 * If no duplicate then also increase count of views for this
	 * question
	 *
	 * @todo try to run this as post-echo method via register_shutdown_function
	 * callback. This is not really resource intensive, but still...
	 * it checks for duplicate, checks viewer ID, etc...
	 * This also runs on every page view, and also since we use fsync when
	 * updating via MongoDoc object, it does require disk write.
	 *
	 *
	 * @return object $this
	 */
	public function increaseViews($inc = 1){
		/**
		 * @todo Don't count question owner view
		 * For this we must be able to get Viewer from Registry
		 *
		 * Filter out duplicate views
		 */
		$viewerId = $this->getRegistry()->Viewer->getUid();

		/**
		 * If guest, then don't check for dups
		 * @todo this will be a problem if we at least don't check
		 * for same session_id or ip address
		 */
		$viewerId = (0 === $viewerId) ? session_id() : $viewerId;

		$ownerID = $this->offsetGet('i_uid');

		d('$viewerId: '.$viewerId.' $ownerID: '.$ownerID);

		if( $viewerId === $ownerID){
			d('viewing own question');

			return $this;
		}

		$iViews = $this->offsetGet('i_views');

		/**
		 * If this is the first view, we will cheat a little
		 * and set the views to 2
		 * There will not be just 1 view, and this way we don't
		 * have to worry about the plural suffix
		 */
		if(0 === $iViews && (1 === $inc)) {
			$inc = 2;
		}

		$collViews = $this->getRegistry()->Mongo->QUESTION_VIEWS;
		$collViews->ensureIndex(array('uid' => 1, 'qid' => 1), array('unique' => true));
		$qid = (int)$this->offsetGet('_id');
		try{
			$collViews->insert(array('qid' => $qid, 'uid' => $viewerId, 'i_ts' => time()), array('safe' => true));
			$this->offsetSet('i_views', ($iViews + (int)$inc) );

			/**
			 * If new value is NOT 1 then set
			 * vw_s (plural suffix) to 's' otherwise
			 * must set to empty string because
			 * by default it's already set to 's'
			 */
			$this->offsetSet('vw_s', 's');

		} catch (\MongoException $e){
			d('duplicate view for qid '.$qid. ' uid: '.$viewerId);
		}

		return $this;

	}


	/**
	 * Process an UP vote for this question
	 *
	 *
	 * @param int $inc could be 1 or -1
	 */
	public function addUpVote($inc = 1){

		if($inc !== 1 && $inc !== -1){
			throw new \InvalidArgumentException('$inc can only be 1 or -1. Was: '.$inc);
		}

		$tmp = (int)$this->offsetGet('i_up');
		$score = (int)$this->offsetGet('i_votes');
		$total = ($score + $inc);

		$this->offsetSet('i_up',  max(0, ($tmp + $inc)) );
		$this->offsetSet('i_votes',  $total );

		/**
		 * Plural extension handling
		 */
		$v_s = (1 === abs($total) ) ? '' : 's';
		$this->offsetSet('v_s', $v_s);

		return $this;
	}


	public function addDownVote($inc = 1){

		if($inc !== 1 && $inc !== -1){
			throw new \InvalidArgumentException('$inc can only be 1 or -1. Was: '.$inc);
		}

		$tmp = (int)$this->offsetGet('i_down');
		$score = (int)$this->offsetGet('i_votes');
		$total = ($score - $inc);

		$this->offsetSet('i_down', max(0, ($tmp + $inc)) );
		/**
		 * Question can have negative score, so we allow it!
		 */
		$this->offsetSet('i_votes', $total );

		/**
		 * Plural extension handling
		 */
		$v_s = (1 === abs($total) ) ? '' : 's';
		$this->offsetSet('v_s', $v_s);

		return $this;
	}


	public function getVotesArray(){

		$a = array(
		'up' => $this->offsetGet('i_up'), 
		'down' => $this->offsetGet('i_down'),
		'score' => $this->offsetGet('i_votes'));

		return $a;
	}


	public function getScore(){
		return $this->offsetGet('i_votes');
	}


	public function addComment(CommentParser $oComment){
		$aKeys = array('_id', 'i_uid', 'i_prnt', 'username', 'avtr', 'b_owner', 'b', 't', 'ts');

		$aComments = $this->getComments();
		d('aComments: '.print_r($aComments, 1));
		/**
		 * Only keep the keys that we need
		 * get rid of keys like hash, i_res
		 * because we don't need them here
		 */
		$aComment = $oComment->getArrayCopy();
		$aComment = array_intersect_key($aComment, array_flip($aKeys));

		$aComments[] = $aComment;

		$this->offsetSet('comments', $aComments);
		$this->increaseCommentsCount();

		/**
		 * A commentor on the question
		 * is considered a question contributor,
		 * so we must add contributor now
		 */
		$this->addContributor($aComment['i_uid']);

		return $this;

	}


	public function getCommentsCount(){
		$aComments = $this->getComments();

		return count($aComments);
	}


	public function increaseCommentsCount(){
		/**
		 * Now increase comments count
		 */
		$commentsCount = $this->getCommentsCount();
		d('$commentsCount '.$commentsCount);

		$this->offsetSet('i_comments', ($commentsCount + 1) );

		return $this;
	}



	/**
	 * Remove one comment from array of comments
	 * then re-save the new array of comments
	 * the numerical keys of array will be reset
	 * Also i_comments value will be updated to the
	 * new count of comments
	 *
	 * (non-PHPdoc)
	 * @see Lampcms\Interfaces.CommentedResource::deleteComment()
	 */
	public function deleteComment($id){

		if(!$this->checkOffset('comments')){
			e('This question does not have any comments');

			return $this;
		}

		$aComments = $this->offsetGet('comments');

		for($i = 0; $i<count($aComments); $i+=1){
			if($aComments[$i]['_id'] == $id){
				d('unsetting comment: '.$i);
				array_splice($aComments, $i, 1);
				break;
			}
		}

		$newCount = count($aComments);
		if( 0 === $newCount){
			$this->offsetUnset('comments');
		} else {
			$this->offsetSet('comments', $aComments);
		}

		$this->offsetSet('i_comments', $newCount );

		return $this;
	}


	/**
	 * Add userid of User to the list
	 * of contributors.
	 * A Contributor is anyone who
	 * has made an answer or a comment
	 * to a question
	 *
	 * @param mixed int | object $oUser object of type User
	 */
	public function addContributor($User){
		if(!is_int($User) && (!is_object($User) || !($User instanceof User))){
			throw new \InvalidArgumentException('Value of $User can be only int or instance of User class. it was: '.var_export($User, true));
		}

		$uid = (is_int($User)) ? $User : $User->getUid();
		$a = $this->getFallback('a_uids', array());
		$a[] = $uid;

		$this->offsetSet('a_uids', $a);

		return $this;
	}


	/**
	 * Remove user id of User $oUser
	 * from array of contributors
	 * Contributors array is not unique,
	 * it can have more than one entry for
	 * the same user if user contributed multiple
	 * times. This way we can remove just one record
	 * and user is still considered a contributor
	 * as long as the same user has contributed other items
	 *
	 * @param mixed int | User $oUser
	 */
	public function removeContributor($User){

		if(!is_int($User) && (!is_object($User) || !($User instanceof User))){
			throw new \InvalidArgumentException('Value of $User can be only int or instance of User class. it was: '.var_export($User, true));
		}

		$changed = false;
		$uid = (is_int($User)) ? $User : $User->getUid();
		$a = $this->getFallback('a_uids', array());
		for($i = 0; $i<count($a); $i+=1){
			if($uid == $a[$i]){
				d('unsetting contributor: '.$uid. ' at array key: ' .$i);
				array_splice($a, $i, 1);
				$changed = true;
				break;
			}
		}

		if($changed){
			$this->offsetSet('a_uids', $a);
		}

		return $this;
	}


	/**
	 * Sets value of lp_u : a link to Last Poster profile
	 * and lp_t a time of last post
	 *
	 * @param User $oUser object of type User who made the last
	 * Answer or Comment to this question
	 *
	 * @return object $this
	 */
	public function setLastAnswerer(User $oUser){

		$this->offsetSet('lp_u', '<a href="'.$oUser->getProfileUrl().'">'.$oUser->getDisplayName().'</a>');
		$this->offsetSet('lp_t', date('F j, Y g:i a T'));

		return $this;
	}


	/**
	 * Getter for 'comments' element
	 * @return array of comments or empty array if
	 * 'comments' element not present in the object
	 *
	 */
	public function getComments(){
		return $this->getFallback('comments', array());
	}


	/**
	 * Get id of question asker
	 *
	 * @return int id of user who asked (owner) of the question
	 */
	public function getQuestionOwnerId(){
		return $this->getOwnerId();
	}

	/**
	 * Get username of asker
	 *
	 * @return string
	 */
	public function getUsername(){
		return $this->offsetGet('username');
	}
}
