<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */


namespace Lampcms;

class QuestionInfo extends LampcmsObject
{

	protected $oQuestion;

	public function __construct(Registry $oRegistry){
		$this->oRegistry = $oRegistry;
	}



	/**
	 * Generates html block with question info.
	 * 
	 * @todo also get count and N first
	 * followers
	 * Followers to be selected from USERS collection
	 * using find() by a_f_q and using limit 5 
	 * and then link to 'show more' if i_flwrs in oQuestion is > 5
	 * 
	 * 
	 * @param Question $oQuestion
	 */
	public function getHtml(Question $oQuestion){
		$this->oQuestion = $oQuestion;

		/**
		 * @todo translate Title string
		 */
		$tagsBlock = \tplBoxrecent::parse(array(
		'title' => 'Question tags',
		'id' => 'question_tags',
		$this->getTags()), false);
		
		
		/**
		 * @todo translate labels used
		 * in tplQuestionsInfo template
		 * 
		 */
		$ret = \tplQuestionInfo::parse(
		array(
				'tags' => $tagsBlock,
				'asked' => TimeAgo::format(new \DateTime($oQuestion['hts'])).' ago',
				'updated' => TimeAgo::format(new \DateTime(date('r', $oQuestion['i_lm_ts']))).' ago',
				'views' => $this->oQuestion['i_views'],
		        'ans_count' => $this->oQuestion->getAnswerCount() 
				)
		);
		
		d('$ret: '.$ret);
		
		return $ret;
	}


	protected function getTags(){
		$aTags = $this->oQuestion['a_tags'];
		d('aTags: '.print_r($aTags, 1));
		
		$res = '';
		$cur = $this->oRegistry->Mongo->QUESTION_TAGS->find(array('tag' => array('$in' => $aTags), 'i_count' => array('$gt' => 0)));
		$count = $cur->count();
		d('count: '.$count);
		
		if($cur && ($count > 0)){
			d('found '.$count.' tags in QUESTION_TAGS collection');
			$res = \tplLinktag::loop($cur);
		}

		d('$res: '.$res);

		return $res;
	}

}
