<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */

/**
 * Template for Edit profile form
 * 
 */
 class tplFormprofile extends Lampcms\Template\Template
 {
 	
 	protected static $vars = array(
 	'token' => '', // 1
	'formTitle' => 'Edit Profile', //2
 	'fn' => '', //3
 	'fn_l' => 'First Name', // 4
 	'mn' => '', // 5
 	'mn_l' => 'Middle Name', //6
 	'ln' => '', // 7
 	'ln_l' => 'Last Name', // 8
 	'dob' => '', //9
 	'dob_l' => 'Date of Birth', //10
 	'dob_d' => 'YYYY/MM/DD, only used for displaying age', //11
 	'country' => '', // 12
 	'country_l' => 'Country', //13
 	'state' => '', //14
 	'state_l' => 'State or Region', // 15
 	'city' => '', //16
 	'city_l' => 'City', //17
 	'zip' => '', //18
 	'zip_l' => 'Postal code (zip)', //19
 	'url' => '', // 20
 	'url_l' => 'Website', //21
 	'description' => '', //22
 	'description_l' => 'About me', //23
 	'description_e' => '', //24
 	'submit' => 'Save', //25
 	'formError' => '', //26
 	'preview' => 'Preview', //27
 	'gender' => '', //28
 	'gender_l' => 'Gender', //29
 	'dob_e' => '', //30
 	'description_d' => 'Plain text only, no html', //31
 	'pictureLabel' => 'Profile picture', //32
 	'avatarSrc' => '', //33
 	'width' => '40', //34
 	'profile_image' => '', //35
 	'changeImage' => 'Change image', //36
 	'avatarTos' => 'Upload Avatar Image. Maximum size of 1Mb<br><span class="smaller">By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.</span>', //37
 	'deleteLabel' => 'Delete this image', //38
 	'uid' => '', //39
 	'hideAvatar' => '', //40
 	'maxAvatarSize' => '2000000', //41
 	'profile_image_e' => '', //42
 	'username' => '', //43
 	'usernameLabel' => '' //44
 	);
 	
 	
 	protected static $tpl = '
 	<form name="epForm" method="POST" action="/index.php" enctype="multipart/form-data" accept-charset="utf-8">
		<input type="hidden" name="a" value="editprofile">
		<input type="hidden" name="uid" value="%39$s">	
		<input type="hidden" name="token" value="%1$s">
<div id="tools" class="form_wrap">
<h1>%2$s</h1>
<div class="form_error">%26$s</div>
<table class="larger vtop eprofile">
<tr><td>%44$s</td><td>%43$s</td></tr>
<tr>
<td>%32$s</td>
 <td>
	<table padding="0"><tr class="profile_img">
	<td width="50px">
	 <img src="%33$s" width="%34$spx" height="%34$spx" class="fl img_avatar">
	 </td>
	 <td>
	 <div class="fl%40$s"> 
	        <!-- <div class="follow ajax slvrbtn change_image rounded4 ">%36$s</div> --> 
	        <!-- <a href="#" id="adel_%39$s" class="ajax delete_image smaller ml10">%38$s</a> -->
	  	<span id="avatar_upload" class="fl _pic_upload"> 
	  	<span class="fl">You may upload your avatar image</span>
	  	  <input type="hidden" name="MAX_FILE_SIZE" value="%41$s" />
	      <input id="id_profile_image" name="profile_image" size="20" type="file" /> 
	      <span class="f_err">%42$s</span>
	      <br><div class="smaller">%37$s</div> 
	    </span>
	   </div> 
		</td></tr></table>
  </td>
</tr>
<tr><td width="40%%">%4$s</td><td width="56%%"><input tabindex="10" type="text" size="35" id="id_fn" name="fn" value="%3$s"></td></tr>
<tr><td>%6$s</td><td><input tabindex="11" type="text" size="35" id="id_mn" name="mn" value="%5$s"></td></tr>
<tr><td>%8$s</td><td><input tabindex="12" type="text" size="35" id="id_ln" name="ln" value="%7$s"></td></tr>
<tr><td>%29$s</td><td><select tabindex="13" name="gender" id="id_gender">%28$s</select></td></tr>
<tr><td>%10$s</td><td><input tabindex="14" type="text" size="10" id="id_dob" name="dob" value="%9$s">
<br><span class="f_err">%30$s</span><div id="dob_d" class="fl cb caption">%11$s</div></td></tr>
<tr><td>%13$s</td><td><select  tabindex="15" name="country">%12$s</select></td></tr>
<tr><td>%15$s</td><td><input tabindex="16" type="text" size="35" id="id_state" name="state" value="%14$s"></td></tr>
<tr><td>%17$s</td><td><input tabindex="17" type="text" size="35" id="id_city" name="city" value="%16$s"></td></tr>
<tr><td>%19$s</td><td><input tabindex="18" type="text" size="7" id="id_zip" name="zip" value="%18$s"></td></tr>
<tr><td>%21$s</td><td><input  tabindex="19" type="text" size="50" id="id_url" name="url" value="%20$s"></td></tr>
<tr><td>%23$s</td><td><textarea  tabindex="20" id="id_description" rows="8" cols="50" class="com_body9" name="description">%22$s</textarea>
<br><span class="fl cb caption">%31$s</span></td></tr>
<tr><td></td><td><div class="form_el">
            	<input  tabindex="20" id="dostuff" name="submit" type="submit" value="%25$s" class="btn_comment"> 
            </div></td></tr>
</table>
</div>
</form>';
 	
 }
 