<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2012 (or current year) Dmitri Snytkine
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */

 
class tplFormEmailOptions extends \Lampcms\Template\Fast
{
	protected static $vars = array(
	'token' => '', // 1
	'formTitle' => 'Current Email Subscription Preferences', //2
	'e_fu' => '', //3
	'e_fu_t' => 'New posts by users I follow', //4
	'e_fu_d' => 'Email me when a new post is made by a user I follow', //5
	
	'e_fq' => '', //6
	'e_fq_t' => 'New activity in questions I follow', // 7
	'e_fq_d' => 'Email me when the new answer is added to questions I follow', //8
	
	'e_ft' => '', //9
	'e_ft_t' => 'New question with a tag I follow', //10
	'e_ft_d' => 'Email me when the a new question is posted and is tagged with one of the tags I follow', //11
	
	'e_ok' => '', //12
	'e_ok_t' => 'Site updates', //13
	'e_ok_d' => 'Receive news and updates from this site\'s administrator', //14
	
	
	'your_email' => '', //15
	'your_email_t' => 'Your Email Address', //16
	'your_email_d' => "The address at which you've chosen to receive messages is:", //17

	'save_l' => 'Save', //18
	
	'e_fc' => '', //19
	'e_fc_t' => 'Reply to my comment', //20
	'e_fc_d' => 'Email me when someone replies to a comment I made', //21
	
	'e_fa' => '', //22
	'e_fa_t' => 'New comment on my answer', //23
	'e_fa_d' => 'Email me when someone comments on the answer I made' //24
	
	);
	
	
	protected static $tpl = '<form name="epForm" method="POST" action="/index.php" accept-charset="utf-8">
		<input type="hidden" name="a" value="emailoptions">	
		<input type="hidden" name="token" value="%1$s">
	<div id="tools" class="email_options">
<h1>%2$s</h1>
<div class="checkboxes">

<input class="checkbox" type="checkbox" name="e_fu" value="e_fu" %3$s>
<h5>%4$s</h5>
<p>%5$s</p>

<input type="checkbox" name="e_fq"  value="e_fq"  %6$s>
<h5>%7$s</h5>
<p>%8$s</p>

<input type="checkbox" name="e_ft"  value="e_ft" %9$s>
<h5>%10$s</h5>
<p>%11$s</p>

<input type="checkbox" name="e_fa"  value="e_fa" %22$s>
<h5>%23$s</h5>
<p>%24$s</p>

<input type="checkbox" name="e_fc"  value="e_fc" %19$s>
<h5>%20$s</h5>
<p>%21$s</p>
<hr>
<input type="checkbox" name="e_ok"  value="e_ok" %12$s>
<h5>%13$s</h5>
<p>%14$s</p>
</div>
<hr>
<h3>%16$s</h3>
<p class="gray">%17$s <strong>%15$s</strong></p>
			<div class="form_el1">
            	<input id="frmsub1" name="submit" type="submit" value="%18$s" class="btn btn-m"> 
            </div>
</div>
</form>';
	
}
