<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is licensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 *       the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attributes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2012 (or current year) Dmitri Snytkine
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */


/**
 * Template contains translation Javascript object
 * This template does not have placeholders
 * as all replacements of this template
 * are done by Translation class from output buffer
 *
 * If you are creating your own translation file for your own
 * language/locale then make sure you add
 * these strings to your .xlf file
 */
class tplTranslations extends \Lampcms\Template\Fast
{

    protected static $tpl = '
<script>
oSL = oSL || {};
oSL.i18n = {
"You must include reason for editing" : "@@You must include reason for editing@@",
"Success" : "@@Success@@",
"Tweet sent" : "@@Tweet sent@@",
"Tweet not sent" : "@@Tweet not sent@@",
"Invite Your Friends" : "@@Invite Your Friends@@",
"Item saved. Redirecting to" : "@@Item saved. Redirecting to@@",
"Return to page" : "@@Return to page@@",
"Go to Profile editor" : "@@Go to Profile editor@@",
"Report to moderator" : "@@Report to moderator@@",
"Close this question" : "@@Close this question@@",
"URL of YouTube Video does not look correct" : "@@URL of YouTube Video does not look correct@@",
"Edit Tags" : "@@Edit Tags@@",
"Delete item" : "@@Delete item@@",
"Delete" : "@@Delete@@",
"Save" : "@@Save@@",
"Shred User" : "@@Shred User@@",
"You must login to perform this action" : "@@You must login to perform this action@@",
"Please login or" : "@@Please login or@@",
"Please login" : "@@Please login@@",
"Click here to register" : "@@Click here to register@@",
"Alert" : "@@Alert@@",
"Please enter your information" : "@@Please enter your information@@",
"Submit" : "@@Submit@@",
"Cancel" : "@@Cancel@@",
"Welcome!" : "@@Welcome!@@",
"Do you want to continue?" : "@@Do you want to continue?@@",
"Continue registration" : "@@Continue registration@@",
"Exit registration" : "@@Exit registration@@",
"Are you sure?" : "@@Are you sure?@@",
"Email address appears to be invalid" : "@@Email address appears to be invalid@@",
"Please enter a valid Email" : "@@Please enter a valid Email@@",
"Please enter email address" : "@@Please enter email address@@",
"Please enter Username" : "@@Please enter Username@@",
"Please enter the text from image" : "@@Please enter the text from image@@",
"Create New Account" : "@@Create New Account@@",
"Retag" : "@@Retag@@",
"close" : "@@close@@",
"Stick" : "@@Stick@@",
"Unstick" : "@@Unstick@@",
"Edit" : "@@Edit@@",
"Reply" : "@@Reply@@",
"Spam" : "@@Spam@@",
"Not a real question" : "@@Not a real question@@",
"Off Topic" : "@@Off Topic@@",
"Turned into unproductive debate" : "@@Turned into unproductive debate@@",
"Duplicate question" : "@@Duplicate question@@",
"Ban poster" : "@@Ban poster@@",
"Reason for delete" : "@@Reason for delete@@",
"Inappropriate" : "@@Inappropriate@@",
"Paste Link to YouTube Video here" : "@@Paste Link to YouTube Video here@@",
"Add YouTube Video" : "@@Add YouTube Video@@",
"Editor ready" : "@@Editor ready@@",
"Loaded content draft from Local Storage" : "@@Loaded content draft from Local Storage@@",
"Comments?" : "@@Comments?@@",
"comment" : "@@comment@@",
"Really delete this comment?" : "@@Really delete this comment?@@",
"At least one tag, max 5 tags separated by spaces" : "@@At least one tag, max 5 tags separated by spaces@@",
"Report" : "@@Report@@",
"Unable to open login window. Please make sure to disable popup blockers in your browser" : "@@Unable to open login window. Please make sure to disable popup blockers in your browser@@"
}
</script>';
}
