<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */


require '../!inc.php';
$tempDir = $Registry->Ini->TEMP_DIR;
echo ' $tempDir: '.$tempDir;

$cookieFile = $tempDir.'github.txt';

$version = curl_version();
$ssl_supported= ($version['features']);
echo '$ssl_supported: '.$ssl_supported;
echo ' flag: '.  CURL_VERSION_SSL;


$aHeaders = array(
'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
'Accept-Charset' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
'Accept-Language' => 'en-US,en;q=0.8',
'Cache-Control' => 'no-cache'
);

$body = null;
try{
	$oCurl = new \Lampcms\Curl();
	$oCurl->setHeaders($aHeaders)
	->setCookieFile($cookieFile);
	$oCurl->getDocument('https://github.com/login');
	$body = $oCurl->getResponseBody();

	//echo $body;
	//exit;

} catch (\Exception $e){

	$s = 'E: '.$e->getMessage().' in '.$e->getFile().' on '.$e->getLine();
	exit($s);
}

$charset = $oCurl->getCharset();
echo ' $charset: '.$charset;
/*$info = $oCurl->getCurlInfo();
 print_r($info);*/

if(!$body){
	exit('something is wrong, no body');
}

echo __LINE__.' ';
$oHTML = new \Lampcms\String\HTMLString();
/**
 * Always use @ to suppress errors in loadHTML!
 * Unless html has previously been fixed with tidy!
 * 
 */
$res = @$oHTML->loadHTML($body);
echo 'loaded: '.$res;
//echo 'body: '.(string)$oHTML->saveHTML();
$forms = $oHTML->xpath('//form[@action = "/session"]');
if(1 !== $forms->length){
	exit('no login form or more than one');
}

$Form = $forms->item(0); // Lampcms\Dom\Element
$formUrl = $Form->getAttribute('action');
echo ' $formUrl: '.$formUrl.' ';

$inputs = $oHTML->xpath('//form[@action = "/session"]//input');
if($inputs->length < 2){
	exit('No form inputs found');
}

$aInputs = array();
for($i = 0; $i < $inputs->length; $i+= 1){
	$item = $inputs->item($i);
	$name = $item->getAttribute('name');
	$aInputs[$name] = $item->getAttribute('value');
}

echo ' $aInputs : '.print_r($aInputs, 1);

$aInputs['login'] = 'wer';
$aInputs['password'] = 'werwe2t';


function get_page($url, $ref = ''){
	global $aHeaders;
	global $cookieFile;
	$oCurl = new \Lampcms\Curl();
	$oCurl->setHeaders($aHeaders)
	->setCookieFile($cookieFile)
	->setReferrer($ref)
	->getDocument($url);

	$body = $oCurl->getResponseBody();

	echo ' body: '.$body;
}




try{
	$oCurl = new \Lampcms\Curl();
	$oCurl->setHeaders($aHeaders)
	->setCookieFile($cookieFile)
	->setReferrer('https://github.com/login');
	$oCurl->getDocument('https://github.com'.$formUrl, null, null, array('formVars' => $aInputs, 'redirect' => 4));

	$body = $oCurl->getResponseBody();

	echo ' body: '.$body;

} catch (\Exception $e){

	$info = $oCurl->getCurlInfo();
	echo 'INFO: '.print_r($info, 1);

	if($e instanceof \Lampcms\HttpRedirectException){
		$newUrl = $e->getNewURI();
		get_page($newUrl, $info['url']);
	}
	$s = 'E: '.$e->getMessage().' in '.$e->getFile().' on '.$e->getLine();
	exit($s);
}
