<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is licensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 *       the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attributes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2012 (or current year) Dmitri Snytkine
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */


ignore_user_abort(true);
set_time_limit(1200);


require '../!inc.php';

if (!defined('BR')) {
    define('BR', "\n<BR>");
}

/**
 * Set names of blocks and location
 * file that you going to import
 *
 * Get these files from MaxMind website:
 * http://www.maxmind.com/app/geolitecity
 *
 * Choose to download GeoLite City in csv format
 * then unzip the downloaded zip file
 * and copy the 2 .csv files in this directory
 * (2 files will approximately 150MB total)
 *
 * Make sure to upload them in ASCII mode
 * (your ftp client/server must be set to transfer the .csv files
 * in ASCII mode)
 *
 * If you want, you may also buy the non-free versions from MixMind,
 * in which case
 * you would change the names of the 2 files below
 * to the names of files that came with your full version of
 * GeoCity .cvs files.
 *
 * Then just run this geo_import.php file via web browser.
 * It may take 5-10 minutes to complete the import,
 * the importer script imports over 4 million records one by one
 * then creating 2 indexes in the database
 *
 * After the importing is done you should delete these .csv files
 * If you don't delete them then anyone can lauhch this file with a browser
 * and it will start the import all over again.
 *
 * If you want to later upgrade to latest files from MaxMind site
 * just upload the new .csv files and run this script again - it will
 * drop the previously imported DB collections and import new files.
 *
 *
 *
 */
$start = microtime(true);
$blocksFile = 'GeoLiteCity-Blocks.csv';

$locationFile = 'GeoLiteCity-Location.csv';

// DO NOT EDIT ANYTHING BELOW

$dir = dirname(__FILE__);
//
$b = $dir . DIRECTORY_SEPARATOR . $blocksFile;
$l = $dir . DIRECTORY_SEPARATOR . $locationFile;
if (!is_readable($l)) {
    throw new \Exception('File ' . $locationFile . ' is not found in this directory ' . $dir . ' or is not readable to php');
}

if (!is_readable($b)) {
    throw new \Exception('File ' . $blocksFile . ' is not found in this directory ' . $dir . ' or is not readable to php');
}


$Importer = new \Lampcms\Geo\Import($Registry->Mongo->getDb(), $b, $l);
$Importer->run();
$end = microtime(true);
echo BR . 'Importing done in ' . ($end - $start) . ' seconds';
