<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */

if (version_compare(PHP_VERSION, '5.3.0')< 0) {
	$err = '<div class="err"><h2>Minimal requirement not met!</h2><h3>No soup for you!</h3>
	<br>This program requires at least PHP version 5.3.0, your version of php: ' . PHP_VERSION. '</div>';
	$s = sprintf($tpl, $err);
	exit($s);
}

$tpl = '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>T1</title>
<style type="text/css"> 
body{
display: block;
width: 100%%;
}
div.main{
width: 100%%;
}
#doc3 {
	margin-top: 20px;
	margin-left: auto; 
	margin-right: auto; 
	width: 760px;
	border: 1px solid black;
	padding: 10px;
}

h1 {
color: green;
}
h2 {
color: red;
}
h3 {
color: darkblue;
}
div {
position: relative;
}

div.e2{
float: left;
width: 98%%;
border-top: 1px dashed black;
padding: 8px;
color: brown;
}
span.ext{
width: 120px;
float: left;
}
span.s2{
width: 500px;
float: left;
position: relative;
border-left: 1px solid black;
padding: 5px;
}
</style> 
</head>
<body>
<div class="main">
<div id="doc3">
%s
</div>
</div>
</body></html>';

/**
 * Must be installed
 */
$aRequired = array('gd' => 'Will not be able to generate CAPTCHA images and to store user-uploaded avatars',
'mongo' => 'Mongo extension is not installed. Please install from http://pecl.php.net/package/mongo');

/**
 * At least one is required
 */
$aUnicode = array('mbstring', 'iconv');

$aOptional = array(
'pdo' => 'Will not be able to use "Similar Questions" feature.', 
'pdo_mysql' => 'Will not be able to use "Similar Questions" feature.', 
'tidy' => 'Will NOT be able to fix bad html strings if user submits bad html', 
'curl' => 'Will not be able to connect to external APIs like Facebook and Twitter or any other', 
'oauth' => 'Will not be able to use Twitter, LinkedIn, Blogger and Tumblr API features',
'apc' => 'Will not be able to take advantage of script caching to gain up to 300% improvement in script loading time'
);

function myfilter(&$val, $key){
	$val = strtolower($val);
}
$aInstalled = get_loaded_extensions();
array_walk($aInstalled, 'myfilter');


foreach($aRequired as $ext => $err){
	$error = '';
	if(!in_array($ext, $aInstalled)){
		$error .= '<div class="err"><h2>Minimal requirement not met!</h2><h3>No soup for you!</h3>
		<div class="e2"><span class="ext">'.$ext.'</span><span class="s1">Not installed '.$err.'</span></div><br>
		<br>
If you need help <a href="http://support.lampcms.com">Our support site</a></div>';
	}

	if(!empty($error)){
		$s = sprintf($tpl, $error);
		exit($s);
	}
}

if(!in_array('mbstring', $aInstalled) && !in_array('iconv', $aInstalled)){
	$err = '<div class="err"><h2>Minimal requirement not met!</h2><h3>No soup for you!</h3><br>
	You don\'t have unicode support</br>
	You need at least one these php extensions<br>
	<strong>mbstring</strong> (preferred) OR <strong>iconv</strong>
	<br>Make sure you have either one of there extensions installed<br>
	and enabled in php and then try this again
	<br>
If you need help visit <a href="http://support.lampcms.com">Our support site</a></div>';
	$s = sprintf($tpl, $err);
	exit($s);
}

foreach($aOptional as $ext => $err){
	$message = '<h1>Congrats! Minimal requirements are met</h1><h3>You will be able to install this program!</h3>';
	if(!in_array($ext, $aInstalled)){
		$message .= '<div class="e2"><span class="ext">'.$ext.' (Optional)</span><span class="s2"> Not installed '.$err.'</span></div><br>';
	}
}

$message .= '<hr><p>Now install the program, rename !config.ini.dist to !config.ini, edit it with your own
site-specific values <b>Make sure to enter correct value for EMAIL_ADMIN</b> address<br>Then navigate
to index.php, click on <em>Create account</em> link and create account using
the same email address as in EMAIL_ADMIN in !config.ini
<br>This will create your administrator account.<br><br>
Make sure to make the www/w/ directory writable<br>
Read complete instuctions <a href="http://www.lampcms.com/installation/">here</a><br>
Enjoy!<br><br>
If you get any errors visit <a href="http://support.lampcms.com">Our support site</a></p>';

$s = sprintf($tpl, $message);
exit($s);

