<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is licensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 *       the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attributes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2012 (or current year) Dmitri Snytkine
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */

namespace Lampcms\Mongo\Schema;

class User
{

    const COLLECTION = 'USERS';

    const PRIMARY = '_id';

    const FIRST_NAME = 'fn';

    const MIDDLE_NAME = 'mn';

    const LAST_NAME = 'ln';

    const PASSWORD = 'pwd';

    const AVATAR = 'avatar';

    const EXTERNAL_AVATAR = 'avatar_external';
    /**
     * User role
     *
     * @var string
     */
    const ROLE = 'role';

    const USERNAME = 'username';

    const USERNAME_LOWERCASE = 'username_lc';

    const SID = 'rs';

    /**
     * @var string value php timezone string
     */
    const TIMEZONE = 'tz';

    /**
     * This is different from registration timestamp
     * as it uses the value of cookie. This cookie is set at first visit to a site
     * User may not register on the first visit but this value will be
     * set during registration
     */
    const FIRST_VISIT_TIMESTAMP = 'i_fv_ts';

    const LAST_ACTIVITY_TIME = 'i_lm_ts';

    const REGISTRATION_TIMESTAMP = 'i_reg_ts';

    const REGISTRATION_TIME = 'date_reg';

    const REPUTATION = 'i_rep';

    const GENDER = 'gender';

    const URL = 'url';

    const DESCRIPTION = 'description';

    const COUNTRY_CODE = 'cc';

    const COUNTRY_NAME = 'cn';

    const STATE = 'state';

    const CITY = 'city';

    const POSTAL_CODE = 'zip';

    const DATA_OF_BIRTH = 'dob';

    const LANG = 'lang';

    const LOCALE = 'locale';

    const EMAIL = 'email';

    const LAST_UPLOAD_TIME = 'i_ts_upld';

    /**
     * Users having this flag set to true
     * will have their Questions and Answers and Comments
     * set to PENDING status, requiring moderation
     * The purpose of this flag is to allow admin or moderator
     * to put user in probation, usually after some warnings about
     * TOS violation.
     *
     */
    const PROBATION_FLAG = 'b_prob';

    /**
     * Counter of approved posts
     * This counter initially set to 0
     * and increments when user post
     * is approved by moderator
     * This counter is used for moderation feature
     * new user must reach certain number of posts
     * before moderation is no longer required.
     * The threshold is defined in !config.ini in NEW_POSTS_MODERATION
     */
    const APPROVED_COUNTER = 'i_ok';

    /**
     * Counter of warnings user received
     * for violating TOS
     */
    const WARNINGS_COUNT = 'i_warn';

    /**
     * Array of warnings user received
     * array of objects, each one has
     * username, userid of moderator,
     * date/time (human readable) and
     * text of warning
     */
    const WARNINGS = 'a_warn';
}
