<?php
/**
 *
 * License, TERMS and CONDITIONS
 *
 * This software is lisensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * ATTRIBUTION REQUIRED
 * 4. All web pages generated by the use of this software, or at least
 * 	  the page that lists the recent questions (usually home page) must include
 *    a link to the http://www.lampcms.com and text of the link must indicate that
 *    the website\'s Questions/Answers functionality is powered by lampcms.com
 *    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 *    The location of the link is not important, it can be in the footer of the page
 *    but it must not be hidden by style attibutes
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This product includes GeoLite data created by MaxMind,
 *  available from http://www.maxmind.com/
 *
 *
 * @author     Dmitri Snytkine <cms@lampcms.com>
 * @copyright  2005-2011 (or current year) ExamNotes.net inc.
 * @license    http://www.gnu.org/licenses/lgpl-3.0.txt GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 * @link       http://www.lampcms.com   Lampcms.com project
 * @version    Release: @package_version@
 *
 *
 */


namespace Lampcms;

class MockAnswer extends Answer
{
	protected $JSON_ENCODED = '{"_id":513,"i_qid":510,"i_uid":3,"i_quid":3,"title":"Mock Stub Post","hash":"327d4e34c496435248e6145dca59065d","username":"user1","ulink":"<a href=\"\/users\/3\/user1\">user1<\/a>","avtr":"http:\/\/127.0.0.5:88\/w\/img\/avatar\/sqr\/3.jpg","i_words":6,"i_up":1,"i_down":0,"i_votes":1,"b":"<span>Text of Mock Answer<br><strong>Mock test<\/strong><br><\/span>","i_ts":1305401334,"i_lm_ts":1305712931,"hts":"May 14, 2011 2:28 pm CDT","v_s":"s","accepted":false,"ip":"127.0.0.1","app":"web","cc":null,"cn":null,"reg":null,"city":null,"zip":null,"lat":null,"lon":null,"a_comments":[{"_id":516,"b":"comment one","username":"user1","i_uid":3,"i_prnt":0,"ts":"Tue, 17 May 2011 20:17:57 -0500","t":"May 17 \'11 at 20:17","avtr":"http:\/\/127.0.0.5:88\/w\/img\/avatar\/sqr\/3.jpg","b_owner":true},{"_id":517,"b":"comment two","username":"user1","i_uid":3,"i_prnt":0,"ts":"Tue, 17 May 2011 20:18:10 -0500","t":"May 17 \'11 at 20:18","avtr":"http:\/\/127.0.0.5:88\/w\/img\/avatar\/sqr\/3.jpg","b_owner":true}],"i_comments":2,"a_edited":[{"username":"user1","i_uid":3,"av":"http:\/\/127.0.0.5:88\/w\/img\/avatar\/sqr\/3.jpg","reason":"for mock test","hts":"May 18, 2011 5:02 am CDT"}]}';

	public function __construct(Registry $oRegistry, array $a = null){
		/**
		 * 3 Lines below to change the database
		 * that's going to be used to the test database
		 *
		 * This in theory is not necessary because boostrap.php
		 * is used in all tests and it defines MONGO_DBNAME as LAMPCMS_TEST
		 * but this is just an extra precaution
		 */
		$aMongo = $oRegistry->Ini->getSection('MONGO');
		$aMongo['db'] = 'LAMPCMS_TEST';
		$oRegistry->Ini->setSection('MONGO', $aMongo);

		$a = \json_decode($this->JSON_ENCODED, true);
		parent::__construct($oRegistry, $a);
	}
}
